### ISSUE TITLE
Hardware: property to determine if on AC or battery

### ISSUE THREAD

**Issue by plfiorini** [lirios/vibe#18]
Ask upower if we are running on AC or battery.

**Comment by azharakbar** [comment]
I am interested in doing this .. 
can u explain me the location of the code .. and what you are expecting from the feature ?

**Comment by plfiorini** [comment]
@azharakbar The change involves the hardware engine (https://github.com/lirios/vibe/blob/develop/declarative/hardware/hardwareengine.cpp).
In particular it needs a `powerSource` property based on an enum with `ACPowerSource` and `BatteryPowerSource` values.

upower knows this information, off the top of my head you can query upower like this to get the initial value:

```cpp
    // Determine power source
    auto message = QDBusMessage::createMethodCall(
                QStringLiteral("org.freedesktop.UPower"),
                QStringLiteral("/org/freedesktop/UPower"),
                QStringLiteral("org.freedesktop.DBus.Properties"),
                QStringLiteral("Get"));
    message << QStringLiteral("org.freedesktop.UPower") << QStringLiteral("OnBattery");
    QDBusPendingReply<QVariant> reply = QDBusConnection::systemBus().asyncCall(message);
    QDBusPendingCallWatcher *watcher = new QDBusPendingCallWatcher(reply);
    connect(watcher, &QDBusPendingCallWatcher::finished, this, [=]() {
        watcher->deleteLater();
        if (!reply.isValid())
            return;

        const bool onBattery = reply.value().toBool();
        m_powerSource = onBattery ? BatteryPowerSource : ACPowerSource;
        Q_EMIT powerSourceChanged();
    });
```

Of course the property can change so you have to connect to the properties changed signal:

```cpp
    QDBusConnection::systemBus().connect(
                QStringLiteral("org.freedesktop.UPower"),
                QStringLiteral("/org/freedesktop/UPower"),
                QStringLiteral("org.freedesktop.DBus.Properties"),
                QStringLiteral("PropertiesChanged"),
                this, SLOT(upowerChanged(QString,QVariantMap,QStringList)));
```

the `QVariantMap` argument contains the properties and the property you are interesed in is `"OnBattery"`.

**Comment by plfiorini** [comment]
You can test this plugging and unplugging the power cord of a laptop if you have one.

**Comment by plfiorini** [comment]
Closing the issue since the repository is being archived.
